import { Typst } from '../src';
import fs from 'fs/promises';
import path from 'path';

async function main() {
    const renderer = new Typst();

    console.log('Testing PDF output...');
    const pdf = await renderer.render({
        code: '= PDF Document\\n\\nThis is a *test* PDF generated by typst-raster.\ \ $ E = m c^2 $',
        format: 'pdf'
    });
    await fs.writeFile(path.join(__dirname, 'test.pdf'), pdf);
    console.log('✓ Rendered test.pdf');

    console.log('Testing PDF with snippet mode...');
    const snippetPdf = await renderer.render({
        code: '$ sum_(k=1)^n k = (n(n+1))/2 $',
        format: 'pdf',
        snippet: true
    });
    await fs.writeFile(path.join(__dirname, 'snippet.pdf'), snippetPdf);
    console.log('✓ Rendered snippet.pdf');

    console.log('Testing PDF with preamble...');
    const preamble = `#set page(fill: rgb("#2b2d31"))
#set text(fill: white)`;
    const preamblePdf = await renderer.render({
        preamble,
        code: '= Dark Theme\\n\\nThis PDF has a dark theme.\ \ $ integral_0^infinity e^(-x^2) dif x = sqrt(pi)/2 $',
        format: 'pdf'
    });
    await fs.writeFile(path.join(__dirname, 'dark-theme.pdf'), preamblePdf);
    console.log('✓ Rendered dark-theme.pdf');

    console.log('\\nAll PDF tests passed! ✓');
}

main().catch(console.error);
